### ISSUE TITLE
test_download_policies tests failing

### ISSUE THREAD

**Issue by seandst** [PulpQE/pulp-smash#349]
Recent smash runs in jenkies have been failing in the test_download_policies modules with tracebacks like this:
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/pulp-smash-runner/pulp-smash/pulp_smash/tests/rpm/api_v2/test_download_policies.py", line 99, in setUpClass
    cls.rpm = client.get(path)
  File "/home/jenkins/workspace/pulp-smash-runner/pulp-smash/pulp_smash/api.py", line 259, in get
    return self.request('GET', url, **kwargs)
  File "/home/jenkins/workspace/pulp-smash-runner/pulp-smash/pulp_smash/api.py", line 319, in request
    requests.request(method, **request_kwargs),
  File "/home/jenkins/workspace/pulp-smash-runner/pulp-smash/pulp_smash/api.py", line 108, in safe_handler
    response.raise_for_status()
  File "/home/jenkins/workspace/pulp-smash-runner/venv/lib/python2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 503 Server Error: Service Unavailable for url: https://host-172-16-46-10.openstacklocal:443/streamer/var/lib/pulp/content/units/rpm/76/78177c241777af22235092f21c3932dd4f0664e1624e5a2c77a201ec70f930/bear-4.1-1.noarch.rpm?policy=eyJleHRlbnNpb25zIjogeyJyZW1vdGVfaXAiOiAiMTcyLjE2LjQ2LjIwOCJ9LCAicmVzb3VyY2UiOiAiL3N0cmVhbWVyL3Zhci9saWIvcHVscC9jb250ZW50L3VuaXRzL3JwbS83Ni83ODE3N2MyNDE3NzdhZjIyMjM1MDkyZjIxYzM5MzJkZDRmMDY2NGUxNjI0ZTVhMmM3N2EyMDFlYzcwZjkzMC9iZWFyLTQuMS0xLm5vYXJjaC5ycG0iLCAiZXhwaXJhdGlvbiI6IDE0NzAzMTgwNjl9;signature=WWkJqZJxCffOLOvghW_BQO_hq8Irpfq-TpO3lXPhvpmxnyzomUfq1p7TXoLXZV2fLrgvLsdsWFSDxIHGz1NYWwatemNhXDJO6W11GdRvd3Fbjkxm1ah7nj64XPzgV9x7Fu1kcnjKI7L3iM22E1cNykdL6qGPPDkrDL6dA--fWMLbwtIz4RvHOgJH2PJhdPQujt89lUZt9EQvOFO0Bz6zAciIcCQQcJUfY00eSEA5p8GSsXSLnzS-21lwwa08kFJPEaFuI1x62snCxJtKKsPJ6btzchWNdr2SQ_SWyhyB_CAgvecUHGuiI6ihlRIEkPU8DeiMByrJWP-A78G3Uz9TYw%3D%3D
```
I've attempted to reproduce these issues manually, but can't replicate the 503 response from the streamer. I'm opening this to try to nail down if it's a test enviornment bug or an actual pulp bug.

Apologies for the non-internet-friendly link, but here's the test run that generated that traceback if you'd like to get more details:
https://pulp-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/pulp-2.9-dev-rhel6/97/testReport/

**Comment by Ichimonji10** [comment]
I can reproduce this issue both on a pair of Pulp 2.9.3 and 2.10.0 systems provisioned yesterday with http://pastebin.com/BKAZhxen.

**Comment by Ichimonji10** [comment]
In short, here's the error:

```
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264) unbound method send() must be called with PulpHTTPAdapter instance as first argument (got PreparedRequest instance instead)
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264) Traceback (most recent call last):
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264)   File "/usr/lib/python2.7/site-packages/nectar/downloaders/threaded.py", line 221, in _fetch
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264)     self.config.read_timeout))
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264)   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264)     return self.request('GET', url, **kwargs)
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264)   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264)     resp = self.send(prep, **send_kwargs)
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264)   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264)     r = adapter.send(request, **kwargs)
Aug 09 15:23:57 example.com pulp_streamer[5933]: nectar.downloaders.threaded:ERROR: (5933-79264) TypeError: unbound method send() must be called with PulpHTTPAdapter instance as first argument (got PreparedRequest instance instead)
```

I'll file a bug, or find one in pulp.plan.io.
