### ISSUE TITLE
'semanage' returned non-zero exit status 1

### ISSUE THREAD

**Issue by midnightercz** [PulpQE/pulp-smash#451]
When selinux is disabled on host system, pulp-smash test suit
pulp_smash.tests.rpm.api_v2.test_rsync_distributor fails with:

    ======================================================================
    ERROR: test suite for <module 'pulp_smash.tests.rpm.api_v2.test_rsync_distributor' from '/root/pulp/pulp-smash/pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py'>
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/nose/suite.py", line 210, in run
        self.setUp()
      File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/nose/suite.py", line 293, in setUp
        self.setupContext(ancestor)
      File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/nose/suite.py", line 316, in setupContext
        try_run(context, names)
      File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/nose/util.py", line 471, in try_run
        return func()
      File "/root/pulp/pulp-smash/pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py", line 98, in setUpModule
        _set_pulp_manage_rsync(cfg, True)
      File "/root/pulp/pulp-smash/pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py", line 179, in _set_pulp_manage_rsync
        return cli.Client(cfg).run(cmd)
      File "/root/pulp/pulp-smash/pulp_smash/cli.py", line 196, in run
        return self.response_handler(completed_process)
      File "/root/pulp/pulp-smash/pulp_smash/cli.py", line 63, in code_handler
        completed_proc.check_returncode()
      File "/root/pulp/pulp-smash/pulp_smash/cli.py", line 108, in check_returncode
        raise subprocess.CalledProcessError(*args)
    subprocess.CalledProcessError: Command '['sudo', 'semanage', 'boolean', '--modify', '--on', 'pulp_manage_rsync']' returned non-zero exit status 1

    ----------------------------------------------------------------------

I suggest, following code should be added before semanage call:

     cmd = ('selinuxenabled',)
     ret = cli.Client(cfg, cli.echo_handler).run(cmd)
     if ret.returncode:
         return

**Comment by Ichimonji10** [comment]
On systems where SELinux is installed and enabled, the `semanage` is not guaranteed to be present. Here's a snippet from a mostly vanilla Fedora 24 system:

```console
[root@fedora-24 ~]# uname -a
Linux fedora-24 4.8.13-200.fc24.x86_64 #1 SMP Fri Dec 9 14:42:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@fedora-24 ~]# getenforce
Enforcing
[root@fedora-24 ~]# which semanage
/usr/bin/which: no semanage in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
```

That said, it seems sensible for Pulp Smash to be able to run even if SELinux is not installed. We have several tests that assume that SELinux is installed, and all of our automation makes use of systems with SELinux, so this will be a continual area of trouble for the foreseeable future.
